---
title: "screen tongue dorsum pileup files"
author: "Tim Read"
date: "October 27, 2015"
output: html_document
---



```{r}
library(dplyr)
source("./SNPs-in-mpileup.R")
```

You can also embed plots, for example:

```{r, echo=FALSE}
SNPs <- read.table("./Data/ST398_specific_SNPs.tab")
pileup_files <- list.files("~/Dropbox/ARTICLES_BY_TDR/2015-staph-metagenome/HMP_PROJECT_SHARED/Mpileup_tongue_dorsum/", full.names = T)

SR_name <- vector()
res1 <- vector()
res2 <- vector()
res3 <- vector()
res4 <- vector()

  for (i in 1:length(pileup_files)) {
  mpu <- read.table(header = T, pileup_files[i])
  r <- regexec("SR.*?_",pileup_files[i])
  SR_name[i] <- unlist(regmatches(pileup_files[i],r))
  SR_name[i] <- gsub("_","",SR_name[i])
  res <- SNPs_in_mpileup(SNPs,mpu)
  res1[i] <- res[1]
  res2[i] <- res[2]
  res3[i] <- res[3]
  res4[i] <- res[4]
}


```
putting the table together and  sorting

```{r}
results <- data.frame(stringsAsFactors = FALSE,cbind(SR_name,res1,res2,res3,res4))
colnames(results) <- c("SR_name","Staph_bases","Staph_median_cov","ST398_specific_bases","ST398_specific_cov")
combined <- read.table("./Data/combined", stringsAsFactors = FALSE)
results_comb <- inner_join(results,combined, by = c("SR_name" = "Sample.Id"))
```




